sass:
  style: :compressed  # Change to :expanded for debugging

permalink: /:year/:month/:day/:title.html

url: https://awscoban.com
baseurl: ""

future: true
debug: false

# Build settings
markdown: kramdown
permalink: pretty
future: true
highlighter: rouge
linenos: true
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

# Disqus post comments
disqus_shortname: cuong

# # number of posts per page. Should be a number such that total pages >= 5. Well, this 
# # is my choice, there is no specific reason for this.

plugins:
  - jekyll-paginate-v2

pagination:
  enabled: true
  collection: 'posts'
  per_page: 10
  permalink: '/page:num/' 
  title: ''
  limit: 0
  sort_field: 'date'
  sort_reverse: false  # Set to false for Chronological order (Oldest first)
  trail: 
    before: 2
    after: 2
    
gems:
  - jekyll-sitemap
  - jekyll-paginate-v2
